name: 'Install Python Dependencies'
description: 'Clones python-greetings and installs pip dependencies'
runs:
  using: "composite"
  steps:
    - name: Stop any running greetings services
      shell: cmd
      run: |
        cmd /c "pm2 delete greetings-app-dev & exit 0"
        cmd /c "pm2 delete greetings-app-stg & exit 0"
        cmd /c "pm2 delete greetings-app-preprod & exit 0"
        cmd /c "pm2 delete greetings-app-prod & exit 0"

    - name: Checkout pipeline repository
      uses: actions/checkout@v4

    - name: Clone python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Create virtual environment and install dependencies
      shell: cmd
      working-directory: python-greetings
      run: |
        python -m venv venv
        venv\Scripts\python -m pip install -r requirements.txt